// INITIALIZATION OPTIONS

#define HELP_INIT       "Write CORSIKA data files into current directory."
#define HELP_LOAD       "Read steering file command line options from database"
#define HELP_NO_LOAD    "Do not read steering file command line options " \
  "from database"
#define HELP_SAVE       "Write steering file command line options to database"

// DATABASE OPTIONS

#define HELP_DB         "Set name of database to read command line options " \
  "and definition of primary"
#define HELP_TABLE      "Set prefix of table from which to read definition " \
  "of the primary"

// CORSIKA OPTIONS

#define HELP_DEBUG      "Set various CORSIKA debug levels. " \
  "0=No debugging. "					\
  "1=CORSIKA debugging option (4.67). "			\
  "2=EGS,FLUKA,QGS debugging (4.68,4.69,4.28) on in addition"
#define HELP_NO_QGS     "Do not emit steering options that require CORSIKA " \
  "to be compiled with QGSJET (4.28)"
#define HELP_NO_CEFFIC  "Do not emit steering options that require CORSIKA " \
  "Cerenkov efficiency option CEFFIC (4.60)"
#define HELP_NO_FLUKA   "Do not emit steering options that require CORSIKA " \
  "to be compiled with FLUKA (4.69)"
#define HELP_NO_MODTRAN "Do not emit steering options that require CORSIKA " \
  "be compiled with ATMEXT. If this option is false then the " \
  "\"-atmosphere\" option set the ATMOSPHERE steering command (4.20). If " \
  "the option is true then the MODATM steering command is used (4.15)"

// RUN OPTIONS

#define HELP_HOST       "Set hostname (4.66)"
#define HELP_USER       "Set username (4.65)"
#define HELP_SEED1      "Set seed of random sequence 1, Hadron (4.3)"
#define HELP_SEED2      "Set seed of random sequence 2, EGS4 (4.3)"
#define HELP_SEED3      "Set seed of random sequence 3, Cerenkov photons (4.3)"
#define HELP_SEED4      "Set seed of random sequence 4, Impact parameter (4.3)"
#define HELP_RUNNO      "Set run number (4.1)"
#define HELP_EVENTNO    "Set first event number (4.2)"
#define HELP_N          "Set number of showers to generate (4.4)"

// TELESCOPE (OPTICS) OPTIONS

#define HELP_TEL_OPTICS_ID "Set the ID of array definition to read from " \
  "the database. If the --db option is selected the definition of the " \
  "telescope array is read from the database. In this case the options " \
  "--tel_rings, --tel_spacing, --tel_elevation and --tel_aperture are "\
  "ignored (4.47,4.62)"
#define HELP_TEL_RINGS  "Set the number of hexagonal rings of telescopes " \
  "in the array. The number of telescopes is 3N(N+1)+1 (4.62)"
#define HELP_TEL_SPACING "Set the spacing between telescopes [in meters] " \
  "(4.62)"
#define HELP_TEL_ELEVATION "Set the elevation of the array [in meters] (4.47)"
#define HELP_TEL_APERTURE "Set the aperture of the telescopes [in meters] " \
  "(4.62)"
#define HELP_TEL_MAX_DIST "Set the maximum distance of the telescopes " \
  "[in meters] from the center of the array. Can be used to make circular " \
  "arrays (4.62)"
#define HELP_TEL_LAYOUT "Set the telescope layout geomoetry. Should be " \
  "\"hex\" or \"square\" (4.62)"

// PRIMARY OPTIONS

#define HELP_GAMMA      "Simulate gamma primaries (4.5)"
#define HELP_PROTON     "Simulate proton primaries (4.5)"
#define HELP_ELECTRON   "Simulate electron primaries (4.5)"
#define HELP_MUON       "Simulate muon primaries (4.5)"
#define HELP_HELIUM     "Simulate helium (A=4, Z=2)  primaries (4.5)"
#define HELP_IRON       "Simulate iron (A=56, Z=26)  primaries (4.5)"
#define HELP_PRIMARY    "Set CORSIKA primary particle definition (4.5)"

#define HELP_ZENITH     "Set fixed target zenith angle (4.8)"
#define HELP_ZENITH_LO  "Set lower limit of isotropic target zenith angle " \
  "distribution (4.8)"
#define HELP_ZENITH_HI  "Set upper limit of isotropic target zenith angle " \
  "distribution (4.8)"
#define HELP_AZIMUTH    "Set fixed target azimuth angle (4.8)"
#define HELP_AZIMUTH_LO "Set lower limit of isotropic target azimuth angle " \
  "distribution (4.9)"
#define HELP_AZIMUTH_HI "Set upper limit of isotropic target azimuth angle " \
  "distribution (4.9)"
#define HELP_VIEWCONE   "Set half-opening angle of primary particle " \
  "arrival direction distribution. If a non zero value is used, CORSIKA " \
  "will generate primaries offset randomly around a FIXED TARGET direction. " \
  "This FIXED TARGET direction is specified with the --zenith and --azimuth " \
  "options OR a SINGLE FIXED TARGET direction can be ranomly generated by" \
  "this program using the --zenith_lo, --zenith_hi, --azimuth_lo and "	\
  "--azimuth_hi options. Note this SINGLE FIXED TARGET direction is used " \
  "all primaries (4.10)"
#define HELP_VIEWCONE_LO "Set inner half-opening angle of primary particle " \
  "arrival direction distribution. See --viewcone option. (4.10)"
#define HELP_VIEWCONE_HI "Set outer half-opening angle of primary particle " \
  "arrival direction distribution. See --viewcone option. (4.10)"
#define HELP_SAMPLING_RADIUS "Set sampling radius [in meters] (4.61)"
#define HELP_ENERGY     "Set energy of primaries [in GeV] (4.6)"
#define HELP_STARTING_DEPTH "Set starting depth of primary [in g/cm^2] (4.12)"

// PRIMARY OPTIONS

#define HELP_ATMOSPHERE "Set atmospheric model. The bahavior of this option " \
  "depends on whether the \"-no_modtran\" option is selected. If it is not " \
  "then a MODTRAN paramaterized atmosphere is used and the ATMOSPHERE " \
  "steering command (4.20) is generated. If \"-no_modtran\" is selected " \
  "then the older ATMMOD steering command is generated (4.15)."
#define HELP_MODTRAN_DATA "Select the name of the parameterized data set " \
  "to emit when the \"-INIT\" option is given. The default value for this " \
  "options depends on the \"-atmosphere\" option. Valid choices are: " \
  "none, do not generate any file; corsika[1-6,9]: generate standard " \
  "CORSIKA files \"atmmodX.dat\". It is important that the \"-atmosphere\" " \
  "option be chosen correctly to use the correct \"atmmodX.dat\" file"
#define HELP_TRANSITION_ENERGY "Set transition energy between low energy " \
  "and high energy hadronic models [in GeV] (4.36)"
#define HELP_MAGNETIC_ARIZONA "Set magnetic field appropriate for Arizona " \
  "(4.21)"
#define HELP_MAGNETIC_ARGENTINA "Set magnetic field appropriate for " \
  "Argentina (4.21)"
#define HELP_MAGNETIC_EQUATOR "Set magnetic field appropriate for Equator " \
  "(4.21)"
#define HELP_MAGNETIC_BX "Set horzontal component of magnetic field " \
  "[in micro-Tesla, north positive] (4.21)"
#define HELP_MAGNETIC_BZ "Set vertical component of magnetic field " \
  "[in micro-Tesla, down positive] (4.21)"
#define HELP_ELEC_MULT_SCAT_FACT "Set electron multiple scattering length " \
  "factor. See CORSIKA documentation (4.38)"
#define HELP_THINNING_ENERGY "Set absolute thinning energy [in GeV] (4.40)"
#define HELP_CUTOFF_HADRON "Set hadronic cut-off energy [in GeV] (4.43)"
#define HELP_CUTOFF_MUON "Set muon cut-off energy [in GeV] (4.43)"
#define HELP_CUTOFF_ELECTRON "Set electron cut-off energy [in GeV] (4.43)"
#define HELP_CUTOFF_GAMMA "Set gamma-ray cut-off energy [in GeV] (4.43)"

// CERENKOV OPTIONS

#define HELP_CERENKOV_EVENT_USE "Set number of times that each particle " \
  "shower is (re)used (4.61)"
#define HELP_CERENKOV_LAMBDA_LO "Set lower limit of Cerenkov wavelength " \
  "[in nm] (4.57)"
#define HELP_CERENKOV_LAMBDA_HI "Set upper limit of Cerenkov wavelength " \
  "[in nm] (4.57)"
#define HELP_CERENKOV_BUNCH "Set Cerenkov bunch size (4.58)"
#define HELP_CERENKOV_QEFF "Enable accounting for Quantum Efficiency in " \
  "Cerenkov photon generation (4.60)"
#define HELP_CERENKOV_ATMO "Enable accounting for Atmospheric absorption in " \
  "Cerenkov photon generation (4.60)"
#define HELP_CERENKOV_MIRROR "Enable accounting for absoption of Cerenkov " \
  "photons on mirror (4.60)"
#define HELP_QEFF_DATA "Select which quantum efficiency data to " \
  "use when accounting for absorption of Cerenkov photons. Choices are " \
  "\"corsika\": original quantum efficiency that is included with CORSIKA"
 #define HELP_ATMO_DATA "Select which atmospheric absorption data to " \
  "use when accounting for transmission of Cerenkov photons. Choices are " \
  "\"corsika\": original reflectivity curve that is included with CORSIKA" 
#define HELP_MIRROR_DATA "Select which mirror reflectivity data to " \
  "use when accounting for absorption of Cerenkov photons. Choices are " \
  "\"corsika\": original reflectivity curve that is included with CORSIKA, " \
  "\"falcone\": reflectivity curve measures by A.Falcone and " \
  "\"double\": reflection from two mirrors with \"falcone\" reflectivity"

// OUTPUT OPTIONS

#define HELP_MAX_EVENT_PRINT "Set maximum number of events for which " \
  "detailed output will be written during the run (4.50)"
#define HELP_MIN_PRINT_ENERGY "Define a cut on the gamma factor of " \
  "particles above which they are printed to MONIOU (4.51)"
#define HELP_PARTICLE_OUTPUT_ENABLE "Enable particle output (4.53)"
#define HELP_TABLE_OUTPUT_ENABLE "Enable tabular output of charged particle " \
  "development (4.53)"
#define HELP_O          "Set name of Cherenkov output file (4.63)"
#define HELP_PARTICLE_OUTPUT_FILE "Set name of particle output file (4.52)"

// IACT OPTIONS

#define HELP_NO_IMPACT_CORRECTION "Disable correction for the impact point "\
  "of charged particles (IACT CODE)"
